# dnsmasq image settings
image:
  repository: quay.io/metal3-io/ironic
  tag: "latest"
  pullPolicy: IfNotPresent

env:
  port: "6180"
  dhcpHosts: "b4:2e:99:97:5c:0d"
  dhcpIgnore: "tag:!known"
  provisioningInterface: "ens18"
  dhcpRange: "192.168.1.75,192.168.1.77,255.255.255.0,12h"
  gatewayIp: "192.168.1.1"
  dnsIp: "192.168.1.252"
# Resource limits and requests
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"
replicaCount: 1
