apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dnsmasq.fullname" . }}-config
  labels:
    app: {{ include "dnsmasq.name" . }}
    release: {{ .Release.Name }}
data:
  HTTPS_PORT: {{ .Values.env.port | toString | quote }}
  DHCP_HOSTS: {{ .Values.env.dhcpHosts | toString | quote }}
  DHCP_IGNORE: {{ .Values.env.dhcpIgnore | toString | quote }}
  PROVISIONING_INTERFACE: {{ .Values.env.provisioningInterface | toString | quote }}
  DHCP_RANGE: {{ .Values.env.dhcpRange | toString | quote }}
  GATEWAY_IP: {{ .Values.env.gatewayIp | toString | quote }}
  DNS_IP: {{ .Values.env.dnsIp | toString | quote }}
