apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dnsmasq.fullname" . }}-config
  labels:
    app: {{ include "dnsmasq.name" . }}
    release: {{ .Release.Name }}
data:
  dnsmasq.conf: |
    {{- range .Values.dnsmasqConfig }}
    {{ . }}
    {{- end }}
