apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dnsmasq.fullname" . }}
  labels:
    app: {{ include "dnsmasq.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dnsmasq.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "dnsmasq.name" . }}
    spec:
      securityContext:
        fsGroup: 994
        runAsUser: 997
      hostNetwork: true
      containers:
        - name: dnsmasq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          command:
            - /bin/rundnsmasq
          ports:
            - containerPort: 67
              name: dhcp
              protocol: UDP
            - containerPort: 69
              name: tftp
              protocol: UDP
          envFrom:
            - configMapRef:
                name: {{ include "dnsmasq.fullname" . }}-config
